### Add an address to the watcher list
POST http://localhost:8080/watcher
Content-Type: application/json

{
 "address": "JRYKGHGPKWHS6ICOWCIQPBM4KS4Z7S4MNG3NCYYXX727IC7UJFQESEWY4E"
}

### List all watched accounts 
GET http://localhost:8080/watcher

### lists all the tracked accounts and their current states.
GET http://localhost:8080/accounts